[project]
name = "iris"
version = "0.1.0"
dependencies = [
    "pydantic~=2.11.3",
    "cryptography~=44.0.0",
    "aiohttp~=3.12.15",
]
description = "Unofficial API client for Dziennik VULCAN e-register from VULCAN"
readme = "README.md"
license = "AGPL-3.0-only"
license-files = ["LICENSE"]
