name: "eduVULCAN Token Fetcher"
slug: "eduvulcan_token_fetcher"
description: "Logs into eduVULCAN and stores a JWT token for a custom integration."
version: "0.1.0"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: "services"
boot: "auto"
init: false
map:
  - config:rw
options:
  login: null
  password: null
schema:
  login: str?
  password: password?
